
# file: basestations.yml

- name: Common tasks in all servers
  hosts: basestations
  roles:
    - common
  tags:
    - pre
    - common


- name: Install basestation
  hosts: basestations
  roles:
    - basestation-installation
  tags:
    - basestation
    - installation


- name: Configure upscript
  hosts: basestations
  sudo: True
  roles:
    - basestation-daemon
  tags:
    - basestation
    - daemon